### ISSUE TITLE
TwoD renderer no longer works with MPAS data

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1050]
The TwoDData renderer no longer works with MPAS data. It looks like the code supporting unstructured meshes wasn't migrated from OpenGL 2.x to modern OpenGL. 

To reproduce:
1. Load Data/MPAS/MPAS_V4.0/x1.40962.output.2012-05-25_00.00.00.nc
2. Enable the 2d renderer with any variable. The code will crash due to OpenGL errors after the call to `glVertexPointer(3, GL_FLOAT, 0, _verts);`

**Comment by StasJ** [comment]
At the time when I was doing the OpenGL migration, vapor wouldn’t load any MPAS datasets and I didn’t know of any other unstructured grids so I couldn’t test it. Shouldn’t take long to fix

**Comment by StasJ** [comment]
I updated the code to OpenGL 3 but I cannot test it because vapor fails to load the MPAS dataset you linked. About 60% of the time vapor doesn't crash but I get nothing drawn. The rest of the time Vapor will crash in DCMPAS::DerivedCoordVertFromCell::ReadRegion (DCMPAS.cpp +1810).

Other renderers do not work for me either. For example if I try adding a wireframe renderer, vapor will crash at UnstructuredGridLayered.cpp +168

**Comment by clyne** [comment]
Can you push your branch so I can access it?

thanks - jc


> On Dec 6, 2018, at 12:13 AM, StasJ <notifications@github.com> wrote:
> 
> I updated the code to OpenGL 3 but I cannot test it because vapor fails to load the MPAS dataset you linked. About 60% of the time vapor doesn't crash but I get nothing drawn. The rest of the time Vapor will crash in DCMPAS::DerivedCoordVertFromCell::ReadRegion (DCMPAS.cpp +1810).
> 
> Other renderers do not work for me either. For example if I try adding a wireframe renderer, vapor will crash at UnstructuredGridLayered.cpp +168
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by StasJ** [comment]
Sure thing

[issue1050](https://github.com/NCAR/VAPOR/tree/issue1050)

**Comment by StasJ** [comment]
Any time is ok, thank you

**Comment by clyne** [comment]
Stas, I just pushed a commit to issue1050 that adds a ‘nverts’  parameter to GetMesh(). Note, nverts is the number of 3-components vertices and 3-component normals returned in verts and normals.

jc


> On Dec 6, 2018, at 2:35 PM, StasJ <notifications@github.com> wrote:
> 
> Any time is ok, thank you
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
@stasj I'm handing this back to you. The WireFrame and Contour renderers are now working, but the refactored OpenGL code is still drawing a black screen.

**Comment by StasJ** [comment]
@clyne I am still unable to load the MPAS dataset you linked. I also tried `Data/MPAS/MPAS-O/hist.mpas-o.0001-01-01_00.00.00.nc`. Both result in a EXEC_BAD_ACCESS when trying to create a TwoDDataRenderer. I am using the most recent version of the branch.
