### ISSUE TITLE
Double input does not allow small values in normal mode

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2934]
1. Pick a double input that maps to a params value.
2. Add a print statement to observe that params value.

With that input:

1. Set the mapping range input to scientific notation mode
2. Input `1e-20`

Notice that params are set to `1e-20`

3. Set the mapping range input to normal mode
4. Input `1e-20`

Notice that params are set to `0`

**Comment by clyne** [comment]
@StasJ I can't reproduce this to verify that it is fixed. There is not enough information. Please provide more detailed instructions

**Comment by StasJ** [comment]
> @StasJ I can't reproduce this to verify that it is fixed. There is not enough information. Please provide more detailed instructions

I updated the instructions.

**Comment by sgpearse** [comment]
When I add 

`std::cout << std::scientific << "value " << value << std::endl;`

To PDoubleInput.cpp:16, I still get 0.000000e+00 when entering 1e-20 to the Slice Rotation X component.

**Comment by clyne** [comment]
@StasJ need more guidance on how to verify if this is indeed fixed.

**Comment by sgpearse** [comment]
A WRF file for reproducing this can be found [here](https://drive.google.com/file/d/1l1-NDC4C0ShW8ZBLFYk2UztrNr_90XyF/view?usp=sharing).

**Comment by StasJ** [comment]
@sgpearse The widget you picked does not use PDoubleInput.
