### ISSUE TITLE
Trying to access incomplete dataset will crash instead of displaying error

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#731]
1. Delete Katrina_data/data/U10 folder
2. Open Katrina
3. Add renderer and select U10
4. Segfault

**Comment by clyne** [comment]
I've created a branch, issue_731, and fixed the problem for the 2D data and partially fixed the Barb renderer. Other renderers and tools still do not recover from a missing variable. I'm kicking this over to Sam and Stas to address the following:

Sam: Statistics
Sam: Plot 
Stas: Contour 
Stas: Barbs 

Note: all renderers/tools should generate an appropriate error message when a selected variable is not present AND recover and work correctly if the offending variable is subsequently changed to a valid variable (Barbs does the former, but not latter).

Note: The is a Renderer::VariableExists() method that can be used to check to see if selected variable(s) are present. Note also, the return from GetGrids() should always be checked for a valid (non-NULL) return.

**Comment by shaomeng** [comment]
Update 4/30/2018:

I've updated the branch to improve on Plot and Statistics tools with a series of commits till d4fb2f1.

**Comment by StasJ** [comment]
2D data is not fixed @clyne:

1. Open Katrina with V10 removed
2. Add and enable TwoDData renderer
3. Select V10

Vapor may crash immediately or after performing some actions.

**Comment by clyne** [comment]
@StasJ 2DData is working fine for me. However, both contour and barbs renders are still problematic. Following the same instructions for reproducing, and enabling the contour renderer results in an immediate crash.

The Barb renderer doesn't crash, but it can't recover either: if you change the invalid variable to a valid one (e.g. set both X & Y components to U10) the app continues to generate error messages

**Comment by StasJ** [comment]
Hmm maybe there is something wrong with my build elsewhere. I didn't push
my changes for barbs and contours yet. I'll try a clean build but if that
doesn't help I'll show you what's is happening.

**Comment by StasJ** [comment]
TFWidget::getRange does not check if the returned Grid is valid @clyne

**Comment by clyne** [comment]
Problem with ErrorReporter has been fixed (the dialog box was made modal to suspend the event loop). 

One problem still remains: Barbs don’t recover after an invalid variable has been selected. If you change the offending variable to a valid one you will continue to get OpenGL errors.

**Comment by sgpearse** [comment]
Vapor is still crashing for me upon the following procedure :(

1. Open Katrina with V10 removed
2. Add and enable TwoDData renderer
3. Select V10

**Comment by clyne** [comment]
When I run this on my Mac it does not crash. However, the ErrorReporter is printing an error message to the terminal:

Uknown Messagebox role -1

@StasJ please take a look at this.

**Comment by StasJ** [comment]
I changed the popup logic to run on the gui thread. This should fix it. @clyne
